
/*SELECT AVAIL_BALANCE
FROM ACCOUNT
GROUP BY AVAIL_BALANCE
HAVING AVG(AVAIL_BALANCE) > (SELECT AVG('AVAIL_BALANCE') FROM ACCOUNT);

SELECT COUNT (CUST_ID), STATE FROM CUSTOMER GROUP BY STATE HAVING COUNT (CUST_ID) > 1;

SELECT 'OPEN_BRANCH_ID', AVG(AVAIL_BALANCE) AS AVG_BALANCE FROM ACCOUNT WHERE STATUS = 'ACTIVE'
GROUP BY OPEN_BRANCH_ID HAVING AVG(AVAIL_BALANCE) > 5000;

# SALARY -> 2ND HIGHEST SALARY

SELECT FIRST_NAME, SALARY FROM EMPLOYEE WHERE SALARY = ( SELECT MAX(SALARY) FROM EMPLOYEE)LIMIT 1 OFFSET N-1;

SELECT * FROM EMPLOYEE ORDER BY SALARY DESC LIMIT 1 OFFSET 1;

SELECT 'FIRST_NAME', 'SALARY' FROM EMPLOYEE ORDER BY SALARY DESC LIMIT 1 OFFSET 1;*/